### PR TITLE
Remove any secrets from pipeline

### PR DESCRIPTION
**Pull request by rogeruiz**
This body of work is going to be used to remove common-resources from the deployment pipeline that are used to put secrets into BOSH deployments. They'll now be managed via CredHub.

### CODE REVIEW

**Comment by jontours** [comment]
@rogeruiz staging and prod secrets still need to be moved to credhub but this is done.

**Comment by jontours** [comment]
All good here to merge.

**Comment by rogeruiz** [comment]
This looks good @jontours. Since I opened this issue I can't approve it, but I think it's a good start for fixing just this deployment. Our other deployments of brokers is going to need this extracted out into the `18F/cg-pipeline-tasks` repository. We can do it afterwards I guess. I can get started on that, but let's make a card on Trello for it.

**Review by rogeruiz — COMMENTED** [review]
:shipit:

**Review by jontours — APPROVED** [review]

**Pull request merged**
